# -*- coding: utf-8 -*-
"""LogisticRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHmeX0pn0M7XZFcQamDPayRkcDSeI5Ws
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Step 2: Create simple dataset
# Study hours vs Pass/Fail
data = {
    'Hours': [1,2,3,4,5,6,7,8,9,10],
    'Pass':  [0,0,0,0,1,1,1,1,1,1]  # 0=Fail, 1=Pass
}

df =pd.DataFrame(data)
print(df)

# Step 3: Split data
X = df[['Hours']]  # Features
y = df['Pass']     # Target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 4: Train Logistic Regression
model = LogisticRegression()
model.fit(X_train, y_train)
# Step 5: Predictions
y_pred = model.predict(X_test)

print("Predictions:", y_pred)
print("Actual     :", y_test.values)


# Step 6: Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Step 7: Visualize the sigmoid curve
X_range = np.linspace(0, 10, 100).reshape(-1,1)
y_prob = model.predict_proba(X_range)[:,1]

plt.scatter(df['Hours'], df['Pass'], color='red', label='Data')
plt.plot(X_range, y_prob, color='blue', label='Logistic Curve')
plt.xlabel("Study Hours")
plt.ylabel("Probability of Passing")
plt.legend()
plt.show()



