# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mKYntyqPTRjC1SVH-xDFsSMp34KUDIN8
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Height & Weight data
X = np.array([
    [120, 25],
    [125, 28],
    [130, 27],
    [150, 45],
    [155, 47],
    [160, 49],
    [170, 70],
    [175, 72],
    [180, 75],
    [185, 78]
])

# Apply K-Means with K=3
kmeans = KMeans(n_clusters=3, n_init=10, random_state=42)
labels = kmeans.fit_predict(X)

centroids = kmeans.cluster_centers_

# Print clusters
print("Cluster centers:\n", centroids)
print("Cluster labels for students:", labels)

# Visualization
plt.figure(figsize=(6,5))
plt.scatter(X[:,0], X[:,1], c=labels, s=100)
plt.scatter(centroids[:,0], centroids[:,1], marker="X", s=200, color="red")
plt.xlabel("Height (cm)")
plt.ylabel("Weight (kg)")
plt.title("K-Means: Students grouped into 3 clusters")
plt.show()