# -*- coding: utf-8 -*-
"""KMEansManualImplementationns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1klE5nK8nL67p93LZzS_dtP6cbfvzutK5
"""

# ================================
# 📘 K-Means Clustering (Manual)
# ================================

import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# Step 1: Define Data
# -----------------------------
data = {
    "C1": {"age": 25, "amount": 500},
    "C2": {"age": 40, "amount": 1000},
    "C3": {"age": 30, "amount": 700},
    "C4": {"age": 18, "amount": 300},
    "C5": {"age": 50, "amount": 1500},
    "C6": {"age": 35, "amount": 1200},
    "C7": {"age": 45, "amount": 1700}
}

# Convert dictionary to numpy array
points = np.array([[v["age"], v["amount"]] for v in data.values()])
labels = list(data.keys())

# -----------------------------
# Step 2: Initialize Centroids
# -----------------------------
# Choose C1 and C2 as initial centroids
centroids = np.array([
    [data["C1"]["age"], data["C1"]["amount"]],
    [data["C2"]["age"], data["C2"]["amount"]]
])

print("Initial Centroids:\n", centroids)

# -----------------------------
# Step 3: K-Means Algorithm
# -----------------------------
def euclidean(a, b):
    return np.sqrt(np.sum((a - b) ** 2))

for iteration in range(5):  # repeat a few times
    clusters = {0: [], 1: []}

    # Assign points to nearest centroid
    for i, point in enumerate(points):
        distances = [euclidean(point, c) for c in centroids]
        cluster_index = np.argmin(distances)
        clusters[cluster_index].append(point)
        print(f"{labels[i]} → Cluster {cluster_index+1} | Distances = {distances}")

    # Compute new centroids
    new_centroids = []
    for i in range(2):
        if clusters[i]:  # avoid empty cluster
            new_centroid = np.mean(clusters[i], axis=0)
            new_centroids.append(new_centroid)
        else:
            new_centroids.append(centroids[i])
    new_centroids = np.array(new_centroids)

    print(f"\nIteration {iteration+1} complete")
    print("New Centroids:\n", new_centroids, "\n")

    # Stop if centroids didn’t change
    if np.allclose(centroids, new_centroids):
        print("✅ Converged!")
        break
    centroids = new_centroids

# -----------------------------
# Step 4: Plot Final Clusters
# -----------------------------
colors = ['red', 'blue']
for i in range(2):
    cluster_points = np.array(clusters[i])
    plt.scatter(cluster_points[:, 0], cluster_points[:, 1], c=colors[i], label=f'Cluster {i+1}')

plt.scatter(centroids[:, 0], centroids[:, 1], c='black', marker='x', s=200, label='Centroids')
plt.title("K-Means Clustering (Manual Implementation)")
plt.xlabel("Age")
plt.ylabel("Amount")
plt.legend()
plt.grid(True)
plt.show()