# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDXT3e3qU_ikrwaNc15Bt0RGZhA1ex5I
"""

# ===== PCA using scikit-learn (simple + clean ML version) =====

import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

# 1️⃣ Create dataset (from your image)
data = {
    'Size_in_canal': [1, 5, 3, 10, 2],
    'No_of_rooms':   [12, 10, 7, 15, 4]
}
df = pd.DataFrame(data)
print("Original Dataset:\n", df)

# 2️⃣ Feature Scaling (best practice for PCA)
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)

# 3️⃣ Apply PCA to reduce dimensions from 2 → 1
pca = PCA(n_components=1)
pca_result = pca.fit_transform(scaled_data)

# 4️⃣ Create DataFrame for reduced data
pca_df = pd.DataFrame(pca_result, columns=['Principal_Component_1'])
print("\nReduced Data (1D after PCA):\n", pca_df)

# 5️⃣ Explained variance (how much info is kept)
print("\nExplained Variance Ratio:", pca.explained_variance_ratio_)
print(f"Total Variance Captured: {pca.explained_variance_ratio_[0]*100:.2f}%")

# 6️⃣ Visualization (for 2D → 1D reduction)
plt.figure(figsize=(6,4))
plt.scatter(df['Size_in_canal'], df['No_of_rooms'], color='blue', label='Original Data', s=80)
plt.title("Original Data (Before PCA)")
plt.xlabel("Size in Canal")
plt.ylabel("No of Rooms")
plt.grid(True)
plt.legend()
plt.show()

plt.figure(figsize=(6,4))
plt.scatter(pca_df.index, pca_df['Principal_Component_1'], color='green', label='After PCA (1D)', s=80)
plt.title("Reduced Data (After PCA)")
plt.xlabel("Sample Index")
plt.ylabel("Principal Component 1")
plt.grid(True)
plt.legend()
plt.show()